# Generated by Django 6.0.2 on 2026-03-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('jobseeker', 'Jobseeker'), ('employer', 'Employer')], default='Jobseeker', max_length=20),
            preserve_default=False,
        ),
    ]
