# Generated by Django 6.0.2 on 2026-03-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_avatar_remove_user_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='add fullname', max_length=30),
            preserve_default=False,
        ),
    ]
