# Generated by Django 6.0.2 on 2026-04-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.JSONField(default=list),
        ),
    ]
