# Generated by Django 6.0.2 on 2026-03-30 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerprofile',
            old_name='languages',
            new_name='skills',
        ),
    ]
